import './shared/styles/globals.css';
import { Raleway } from 'next/font/google';
import NextProvider from '@/app/shared/NextProvider';
import clsx from 'clsx';


const raleway = Raleway({
	subsets: ['latin'],
	variable: '--font-sans',
});
export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
	return (
		<html lang="en">
		<body className={clsx(`font-sans ${raleway.variable}`, 'bg-hero-pattern max-w-full')}>
		<NextProvider>
			{children}
		</NextProvider>
		</body>
		</html>
	);
}